# yaml-language-server: $schema=https://raw.githubusercontent.com/DataDog/system-tests/refs/heads/main/utils/manifest/schema.json
---
manifest:
  tests/apm_tracing_e2e/test_single_span.py::Test_SingleSpan:
    - declaration: missing_feature (Single Spans is not available in agents pre 7.40)
      component_version: '<7.40.0'
  tests/integrations/test_open_telemetry.py::Test_MsSql::test_error_exception_event:
    - component_version: "<7.75.0-0"
      declaration: irrelevant (new behavior implement in 7.75.0)
  tests/integrations/test_open_telemetry.py::Test_MsSql::test_error_message:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/integrations/test_open_telemetry.py::Test_MsSql::test_error_type_and_stack:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/integrations/test_open_telemetry.py::Test_MySql::test_error_exception_event:
    - component_version: "<7.75.0-0"
      declaration: irrelevant (new behavior implement in 7.75.0)
  tests/integrations/test_open_telemetry.py::Test_MySql::test_error_message:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/integrations/test_open_telemetry.py::Test_MySql::test_error_type_and_stack:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/integrations/test_open_telemetry.py::Test_Postgres::test_error_exception_event:
    - component_version: "<7.75.0-0"
      declaration: irrelevant (new behavior implement in 7.75.0)
  tests/integrations/test_open_telemetry.py::Test_Postgres::test_error_message:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/integrations/test_open_telemetry.py::Test_Postgres::test_error_type_and_stack:
    - component_version: ">=7.75.0-0"
      declaration: irrelevant (has been replaced by test_error_exception_event)
  tests/otel_tracing_e2e/test_e2e.py::Test_OTelLogE2E: v7.48.0
  tests/test_sampling_rates.py::Test_SamplingRates: v7.33.0
  tests/test_telemetry.py::Test_APMOnboardingInstallID: v7.50.0
  tests/test_v1_payloads.py::Test_V1Payloads: v7.73.0-devel
