---
tests/:
  otel_tracing_e2e/:
    test_e2e.py:
      Test_OTelLogE2E: v7.48.0
  test_sampling_rates.py:
    Test_SamplingRates: v7.33.0
  test_telemetry.py:
    Test_APMOnboardingInstallID: v7.50.0
  test_v1_payloads.py:
    Test_V1Payload: missing_feature