---
tests/:
  k8s_lib_injection/:
    test_k8s_lib_injection_profiling.py:
      TestK8sLibInjectioProfilingClusterEnabled: v7.57.0
      TestK8sLibInjectioProfilingClusterOverride: v7.57.0
      TestK8sLibInjectioProfilingDisabledByDefault: v7.57.0
