tests/:
  appsec/:
    api_security/:
      test_schemas.py:
        Test_Scanners: missing_feature
        Test_Schema_Request_Cookies: v0.94.0
        Test_Schema_Request_FormUrlEncoded_Body: v0.94.0
        Test_Schema_Request_Headers: v0.94.0
        Test_Schema_Request_Json_Body: missing_feature
        Test_Schema_Request_Path_Parameters: missing_feature
        Test_Schema_Request_Query_Parameters: v0.94.0
        Test_Schema_Response_Body: missing_feature
        Test_Schema_Response_Headers: v0.94.0
    iast/:
      sink/:
        test_command_injection.py:
          TestCommandInjection: missing_feature
        test_hardcoded_secrets.py:
          Test_HardcodedSecrets: missing_feature          
        test_header_injection.py:
          TestHeaderInjection: missing_feature
        test_hsts_missing_header.py: 
          Test_HstsMissingHeader: missing_feature
        test_insecure_cookie.py:
          TestInsecureCookie: missing_feature
        test_ldap_injection.py:
          TestLDAPInjection: missing_feature
        test_no_httponly_cookie.py:
          TestNoHttponlyCookie: missing_feature
        test_no_samesite_cookie.py:
          TestNoSamesiteCookie: missing_feature
        test_nosql_mongodb_injection.py:
          TestNoSqlMongodbInjection: missing_feature
        test_path_traversal.py:
          TestPathTraversal: missing_feature
        test_sql_injection.py:
          TestSqlInjection: missing_feature
        test_ssrf.py:
          TestSSRF: missing_feature
        test_trust_boundary_violation.py:
          Test_TrustBoundaryViolation: missing_feature
        test_unvalidated_redirect.py:
          TestUnvalidatedHeader: missing_feature
          TestUnvalidatedRedirect: missing_feature
        test_unvalidated_redirect_forward.py:
          TestUnvalidatedForward: missing_feature
        test_weak_cipher.py:
          TestWeakCipher: missing_feature
        test_weak_hash.py:
          TestWeakHash: missing_feature
        test_weak_randomness.py:
          TestWeakRandomness: missing_feature
        test_xcontent_sniffing.py:
          Test_XContentSniffing: missing_feature        
        test_xpath_injection.py:
          TestXPathInjection: missing_feature
      source/:
        test_body.py:
          TestRequestBody: missing_feature
        test_cookie_name.py:
          TestCookieName: missing_feature
        test_cookie_value.py:
          TestCookieValue: missing_feature
        test_header_name.py:
          TestHeaderName: missing_feature
        test_header_value.py:
          TestHeaderValue: missing_feature
        test_multipart.py:
          TestMultipart: missing_feature
        test_parameter_name.py:
          TestParameterName: missing_feature
        test_parameter_value.py:
          TestParameterValue: missing_feature
        test_path.py:
          TestPath: missing_feature
        test_uri.py:
          TestURI: missing_feature
    waf/:
      test_addresses.py:
        Test_BodyRaw: v0.1.0
        Test_BodyUrlEncoded: v0.1.0
        Test_Cookies: v0.1.0
        Test_FullGrpc: missing_feature
        Test_GraphQL: missing_feature
        Test_Headers: v0.1.0
        Test_Lambda: missing_feature
        Test_PathParams: v0.2.1
        Test_UrlQuery: v0.1.0
        Test_UrlQueryKey: v0.3.2
        Test_UrlRaw: v0.1.0
        Test_gRPC: missing_feature
      test_blocking.py:
        Test_Blocking: v0.7.0
        Test_CustomBlockingResponse: v0.7.0
      test_custom_rules.py:
        Test_CustomRules: v0.8.1
      test_exclusions.py:
        Test_Exclusions: v0.7.0
      test_miscs.py:
        Test_404: v0.1.0
        Test_CorrectOptionProcessing: v0.1.0
        Test_MultipleAttacks: v0.1.0
        Test_MultipleHighlight: v0.2.0
      test_reports.py:
        Test_Monitoring: v0.3.0
      test_rules.py:
        Test_CommandInjection: v0.1.0
        Test_HttpProtocol: v0.1.0
        Test_JavaCodeInjection: v0.1.0
        Test_JsInjection: v0.1.0
        Test_LFI: v0.1.0
        Test_NoSqli: v0.1.0
        Test_PhpCodeInjection: v0.1.0
        Test_RFI: v0.1.0
        Test_SQLI: v0.1.0
        Test_SSRF: v0.1.0
        Test_Scanners: v0.1.0
        Test_XSS: v0.1.0
    test_alpha.py:
      Test_Basic: v0.2.1
    test_blocking_addresses.py:
      Test_BlockingAddresses: v0.7.0
      Test_Blocking_request_body: v0.7.0
      Test_Blocking_request_cookies: v0.7.0
      Test_Blocking_request_headers: v0.7.0
      Test_Blocking_request_method: v0.7.0
      Test_Blocking_request_path_params: v0.7.0
      Test_Blocking_request_query: v0.7.0
      Test_Blocking_request_uri: v0.7.0
      Test_Blocking_response_headers: v0.7.0
      Test_Blocking_response_status: v0.7.0
      Test_Suspicious_Request_Blocking: missing_feature (v0.7.0 but test is not implemented)
    test_conf.py:
      Test_RuleSet_1_3_1: v0.3.0
      Test_StaticRuleSet: v0.1.0
    test_customconf.py:
      Test_ConfRuleSet: v0.3.0
      Test_CorruptedRules: v0.3.0
      Test_MissingRules: v0.3.0
      Test_NoLimitOnWafRules: v0.3.0
    test_event_tracking.py:
      Test_CustomEvent: v0.6.0
      Test_UserLoginFailureEvent: v0.6.0
      Test_UserLoginSuccessEvent: v0.6.0
    test_ip_blocking_full_denylist.py:
      Test_AppSecIPBlockingFullDenylist: v0.7.0
    test_logs.py:
      Test_Standardization: v0.1.0
    test_reports.py:
      Test_HttpClientIP: v0.3.0
      Test_RequestHeaders: v0.2.0
      Test_StatusCode: v0.1.0
    test_request_blocking.py:
      Test_AppSecRequestBlocking: v0.7.0
    test_runtime_activation.py:
      Test_RuntimeActivation: v0.7.0
    test_shell_execution.py:
      Test_ShellExecution: missing_feature
    test_traces.py:
      Test_AppSecEventSpanTags: v0.1.0
      Test_AppSecObfuscator: v0.3.0
      Test_CollectRespondHeaders: v0.2.2
      Test_DistributedTraceInfo: missing_feature (test not implemented)
      Test_RetainTraces: v0.1.0
    test_user_blocking_full_denylist.py:
      Test_UserBlocking_FullDenylist: v0.7.2
  remote_config/:
    test_remote_configuration.py:
      Test_RemoteConfigurationUpdateSequenceASMDD: v0.7.0
      Test_RemoteConfigurationUpdateSequenceASMDDNoCache: v0.7.0
      Test_RemoteConfigurationUpdateSequenceFeatures: v0.7.0
      Test_RemoteConfigurationUpdateSequenceFeaturesNoCache: v0.7.0
  test_standard_tags.py:
    Test_StandardTagsClientIp: v0.4.4
