---
refs:
  - &ref_0_0_1 "0.0.1"
manifest:
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids: "0.0.1"
  tests/parametric/test_config_consistency.py: "missing_feature"
  tests/parametric/test_crashtracking.py: "missing_feature"
  tests/parametric/test_dynamic_configuration.py: "missing_feature"
  tests/parametric/test_headers_b3.py: "missing_feature"
  tests/parametric/test_headers_b3multi.py: "missing_feature"
  tests/parametric/test_headers_baggage.py::Test_Headers_Baggage: "missing_feature"
  tests/parametric/test_headers_baggage.py::Test_Headers_Baggage_Span_Tags: "missing_feature"
  tests/parametric/test_headers_datadog.py::Test_Headers_Datadog: "0.0.1"
  tests/parametric/test_headers_none.py::Test_Headers_None: "0.0.1"
  tests/parametric/test_headers_precedence.py::Test_Headers_Precedence: "0.0.1"
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext: "0.0.1"
  tests/parametric/test_headers_tracestate_dd.py::Test_Headers_Tracestate_DD: "0.0.1"
  tests/parametric/test_library_tracestats.py::Test_Library_Tracestats: "missing_feature"
  tests/parametric/test_otel_api_interoperability.py::Test_Otel_API_Interoperability: "missing_feature"
  tests/parametric/test_otel_env_vars.py::Test_Otel_Env_Vars: "incomplete_test_app (/trace/config endpoint is not implemented)"
  tests/parametric/test_otel_logs.py: "missing_feature"
  tests/parametric/test_otel_metrics.py: "missing_feature"
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods: "0.0.1"
  tests/parametric/test_otel_span_with_baggage.py::Test_Otel_Span_With_Baggage: "missing_feature"
  tests/parametric/test_otel_tracer.py::Test_Otel_Tracer: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Add_Link: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Finish: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Error: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Meta: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Metric: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Resource: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Start: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Baggage: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Config: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Crash: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Current_Span: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Extract_Headers: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Flush: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Inject_Headers: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Events: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Set_Name: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Start: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Otel_Baggage: "missing_feature"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Otel_Current_Span: "0.0.1"
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Write_Log: "missing_feature"
  tests/parametric/test_partial_flushing.py::Test_Partial_Flushing: "missing_feature"
  tests/parametric/test_process_discovery.py: "missing_feature"
  tests/parametric/test_sampling_span_tags.py: "missing_feature"
  tests/parametric/test_span_events.py: "missing_feature"
  tests/parametric/test_span_links.py::Test_Span_Links: "missing_feature"
  tests/parametric/test_span_sampling.py: "missing_feature"
  tests/parametric/test_telemetry.py::Test_Consistent_Configs: "missing_feature"
  tests/parametric/test_telemetry.py::Test_Defaults: "missing_feature"
  tests/parametric/test_telemetry.py::Test_Environment: "missing_feature"
  tests/parametric/test_telemetry.py::Test_Stable_Configuration_Origin: "missing_feature"
  tests/parametric/test_telemetry.py::Test_TelemetryInstallSignature: "missing_feature"
  tests/parametric/test_telemetry.py::Test_TelemetrySCAEnvVar: "missing_feature"
  tests/parametric/test_telemetry.py::Test_TelemetrySSIConfigs: "missing_feature"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Basic: "0.0.1"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Globs: "0.0.1"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Globs_Feb2024_Revision: "0.0.1"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Resource: "0.0.1"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Tags: "missing_feature"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Tags_Feb2024_Revision: "missing_feature"
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_With_W3C: "missing_feature"
  tests/parametric/test_tracer.py: "missing_feature"
  tests/parametric/test_tracer_flare.py::TestTracerFlareV1: "missing_feature"
  tests/test_v1_payloads.py: "missing_feature"
