---
refs:
  - &ref_0_0_1 "0.0.1"
tests/:
  parametric/:
    test_feature_flag_exposure/:
      test_feature_flag_exposure.py:
        Test_Feature_Flag_Exposure: *ref_0_0_1
    test_128_bit_traceids.py:
      Test_128_Bit_Traceids: *ref_0_0_1
    test_config_consistency.py: *ref_0_0_1
    test_crashtracking.py: *ref_0_0_1
    test_dynamic_configuration.py: *ref_0_0_1
    test_headers_b3.py: *ref_0_0_1
    test_headers_b3multi.py: *ref_0_0_1
    test_headers_baggage.py:
      Test_Headers_Baggage: *ref_0_0_1
      Test_Headers_Baggage_Span_Tags: *ref_0_0_1
    test_headers_datadog.py:
      Test_Headers_Datadog: *ref_0_0_1
    test_headers_none.py:
      Test_Headers_None: *ref_0_0_1
    test_headers_precedence.py:
      Test_Headers_Precedence: *ref_0_0_1
    test_headers_tracecontext.py:
      Test_Headers_Tracecontext: *ref_0_0_1
    test_headers_tracestate_dd.py:
      Test_Headers_Tracestate_DD: *ref_0_0_1
    test_library_tracestats.py:
      Test_Library_Tracestats: *ref_0_0_1
    test_otel_api_interoperability.py:
      Test_Otel_API_Interoperability: *ref_0_0_1
    test_otel_env_vars.py:
      Test_Otel_Env_Vars: incomplete_test_app (/trace/config endpoint is not implemented)
    test_otel_logs.py: *ref_0_0_1
    test_otel_metrics.py: *ref_0_0_1
    test_otel_span_methods.py:
      Test_Otel_Span_Methods: *ref_0_0_1
    test_otel_span_with_baggage.py:
      Test_Otel_Span_With_Baggage: *ref_0_0_1
    test_otel_tracer.py:
      Test_Otel_Tracer: *ref_0_0_1
    test_parametric_endpoints.py:
      Test_Parametric_DDSpan_Add_Link: *ref_0_0_1
      Test_Parametric_DDSpan_Finish: *ref_0_0_1
      Test_Parametric_DDSpan_Set_Error: *ref_0_0_1
      Test_Parametric_DDSpan_Set_Meta: *ref_0_0_1
      Test_Parametric_DDSpan_Set_Metric: *ref_0_0_1
      Test_Parametric_DDSpan_Set_Resource: *ref_0_0_1
      Test_Parametric_DDSpan_Start: *ref_0_0_1
      Test_Parametric_DDTrace_Baggage: *ref_0_0_1
      Test_Parametric_DDTrace_Config: *ref_0_0_1
      Test_Parametric_DDTrace_Crash: *ref_0_0_1
      Test_Parametric_DDTrace_Current_Span: *ref_0_0_1
      Test_Parametric_DDTrace_Extract_Headers: *ref_0_0_1
      Test_Parametric_DDTrace_Flush: *ref_0_0_1
      Test_Parametric_FFE_Start: *ref_0_0_1
      Test_Parametric_Inject_Headers: *ref_0_0_1
      Test_Parametric_OtelSpan_Events: *ref_0_0_1
      Test_Parametric_OtelSpan_Set_Name: *ref_0_0_1
      Test_Parametric_OtelSpan_Start: *ref_0_0_1
      Test_Parametric_Otel_Baggage: *ref_0_0_1
      Test_Parametric_Otel_Current_Span: *ref_0_0_1
      Test_Parametric_Write_Log: *ref_0_0_1
    test_partial_flushing.py:
      Test_Partial_Flushing: *ref_0_0_1
    test_process_discovery.py: *ref_0_0_1
    test_sampling_span_tags.py: *ref_0_0_1
    test_span_events.py: *ref_0_0_1
    test_span_links.py:
      Test_Span_Links: *ref_0_0_1
    test_span_sampling.py: *ref_0_0_1
    test_telemetry.py:
      Test_Consistent_Configs: *ref_0_0_1
      Test_Defaults: *ref_0_0_1
      Test_Environment: *ref_0_0_1
      Test_Stable_Configuration_Origin: *ref_0_0_1
      Test_TelemetryInstallSignature: *ref_0_0_1
      Test_TelemetrySCAEnvVar: *ref_0_0_1
      Test_TelemetrySSIConfigs: *ref_0_0_1
    test_trace_sampling.py:
      Test_Trace_Sampling_Basic: *ref_0_0_1
      Test_Trace_Sampling_Globs: *ref_0_0_1
      Test_Trace_Sampling_Globs_Feb2024_Revision: *ref_0_0_1
      Test_Trace_Sampling_Resource: *ref_0_0_1
      # dd-trace-rs samples at span start, so any trace that doesn't start the span with the necessary attributes
      # won't match the sampling rule. We want to fix this in the future, making sampling lazy.
      # The tests in these suites that xpass also have this issue, we just end up with the right value by default.
      Test_Trace_Sampling_Tags: *ref_0_0_1
      Test_Trace_Sampling_Tags_Feb2024_Revision: *ref_0_0_1
      Test_Trace_Sampling_With_W3C: *ref_0_0_1
    test_tracer.py: *ref_0_0_1
    test_tracer_flare.py:
      TestTracerFlareV1: *ref_0_0_1
  test_feature_flag_exposures.py:
    Test_FFE_Exposure_Events: *ref_0_0_1
    Test_FFE_Exposure_Events_Empty: *ref_0_0_1
    Test_FFE_Exposure_Events_Errors: *ref_0_0_1
  test_v1_payloads.py: *ref_0_0_1
