# yaml-language-server: $schema=https://raw.githubusercontent.com/DataDog/system-tests/refs/heads/main/utils/manifest/schema.json
---
refs:
  - &ref_0_0_1 "0.0.1"
manifest:
  tests/appsec/api_security/test_endpoint_fallback.py: missing_feature
  tests/ffe/test_dynamic_evaluation.py: missing_feature
  tests/ffe/test_exposures.py: missing_feature
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids: 0.0.1
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3multi_128_bit_generation_disabled: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3multi_128_bit_generation_enabled: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3multi_128_bit_propagation: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3multi_128_bit_propagation_and_generation: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3single_128_bit_generation_disabled: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3single_128_bit_generation_enabled: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3single_128_bit_propagation: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_b3single_128_bit_propagation_and_generation: missing_feature (propagation style not supported)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_datadog_128_bit_generation_disabled: missing_feature (128 bit traceid is always enabled)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_datadog_128_bit_generation_enabled: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_datadog_128_bit_generation_enabled_by_default: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_generation_disabled: missing_feature (128 bit traceid is always enabled)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_generation_enabled: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_propagation: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_propagation_tid_in_chunk_root: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_propagation_tid_in_trace_chunk: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_propagation_tid_inconsistent: missing_feature (APMSP-2059)
  tests/parametric/test_128_bit_traceids.py::Test_128_Bit_Traceids::test_w3c_128_bit_propagation_tid_malformed: missing_feature (APMSP-2059)
  tests/parametric/test_config_consistency.py: missing_feature
  tests/parametric/test_crashtracking.py: missing_feature
  tests/parametric/test_dynamic_configuration.py: missing_feature
  tests/parametric/test_ffe/test_dynamic_evaluation.py::Test_Feature_Flag_Dynamic_Evaluation: missing_feature
  tests/parametric/test_headers_b3.py: missing_feature
  tests/parametric/test_headers_b3multi.py: missing_feature
  tests/parametric/test_headers_baggage.py::Test_Headers_Baggage: missing_feature
  tests/parametric/test_headers_baggage.py::Test_Headers_Baggage_Span_Tags: missing_feature
  tests/parametric/test_headers_datadog.py::Test_Headers_Datadog: 0.0.1
  tests/parametric/test_headers_none.py::Test_Headers_None: 0.0.1
  tests/parametric/test_headers_precedence.py::Test_Headers_Precedence: 0.0.1
  ? tests/parametric/test_headers_precedence.py::Test_Headers_Precedence::test_headers_precedence_propagationstyle_default_tracecontext_datadog
  : 'irrelevant (Issue: tracecontext,Datadog was never the default configuration)'
  tests/parametric/test_headers_precedence.py::Test_Headers_Precedence::test_headers_precedence_propagationstyle_legacy: irrelevant (Implements the new 'datadog,tracecontext' default)
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext: 0.0.1
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext::test_traceparent_duplicated: missing_feature (multi-value header extraction is not supported by otel rust yet)
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext::test_tracestate_empty_header: missing_feature (multi-value header extraction is not supported by otel rust yet)
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext::test_tracestate_multiple_headers_different_keys: missing_feature (multi-value header extraction is not supported by otel rust yet)
  tests/parametric/test_headers_tracecontext.py::Test_Headers_Tracecontext::test_tracestate_ows_handling: missing_feature (Invalid tracestate keys for OpenTelemetry's implementation)
  tests/parametric/test_headers_tracestate_dd.py::Test_Headers_Tracestate_DD: 0.0.1
  tests/parametric/test_headers_tracestate_dd.py::Test_Headers_Tracestate_DD::test_headers_tracestate_dd_propagate_propagatedtags: missing_feature (can't guarantee the order of strings in the tracestate since they came from the map.)
  tests/parametric/test_library_tracestats.py::Test_Library_Tracestats: missing_feature
  tests/parametric/test_llm_observability/: irrelevant (library does not implement LLM Observability)
  tests/parametric/test_otel_api_interoperability.py::Test_Otel_API_Interoperability: missing_feature
  tests/parametric/test_otel_env_vars.py::Test_Otel_Env_Vars: incomplete_test_app (/trace/config endpoint is not implemented)
  tests/parametric/test_otel_logs.py: missing_feature
  tests/parametric/test_otel_metrics.py: v0.3.0
  ? tests/parametric/test_otel_metrics.py::Test_Otel_Metrics_Api_Instrument::test_otel_histogram_add_non_negative_and_negative_values
  : missing_feature (OpenTelemetry Rust SDK does not filter negative values for Histogram.record(). This is a bug in the upstream SDK)
  tests/parametric/test_otel_metrics.py::Test_Otel_Metrics_Host_Name::test_hostname_from_dd_hostname: missing_feature
  tests/parametric/test_otel_metrics.py::Test_Otel_Metrics_Telemetry::test_telemetry_metrics_grpc: missing_feature
  tests/parametric/test_otel_metrics.py::Test_Otel_Metrics_Telemetry::test_telemetry_metrics_http_protobuf: missing_feature
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods: 0.0.1
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_get_span_context: missing_feature (APMSP-2059)
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_set_attributes_different_types_legacy: missing_feature (Old array encoding not supported)
  ? tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_extended_reserved_attributes_overrides_analytics_event
  : missing_feature (Not implemented)
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_started_with_link_from_another_span: missing_feature (APMSP-2059)
  tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_started_with_link_from_other_spans: missing_feature (APMSP-2059)
  ? tests/parametric/test_otel_span_methods.py::Test_Otel_Span_Methods::test_otel_span_strict_reserved_attributes_overrides_analytics_event
  : missing_feature (Not implemented)
  tests/parametric/test_otel_span_with_baggage.py::Test_Otel_Span_With_Baggage: missing_feature
  tests/parametric/test_otel_tracer.py::Test_Otel_Tracer: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Add_Link: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Finish: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Error: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Meta: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Metric: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Set_Resource: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDSpan_Start: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Baggage: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Config: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Crash: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Current_Span: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Extract_Headers: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_DDTrace_Flush: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_FFE_Start: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Inject_Headers: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Events: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Set_Name: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_OtelSpan_Start: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Otel_Baggage: missing_feature
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Otel_Current_Span: 0.0.1
  tests/parametric/test_parametric_endpoints.py::Test_Parametric_Write_Log: missing_feature
  tests/parametric/test_partial_flushing.py::Test_Partial_Flushing: missing_feature
  tests/parametric/test_process_discovery.py: missing_feature
  tests/parametric/test_sampling_manual.py::Test_Manual_Sampling: missing_feature
  tests/parametric/test_sampling_span_tags.py: missing_feature
  tests/parametric/test_span_events.py: missing_feature
  tests/parametric/test_span_links.py::Test_Span_Links: missing_feature
  tests/parametric/test_span_sampling.py: missing_feature
  tests/parametric/test_telemetry.py::Test_Consistent_Configs: missing_feature
  tests/parametric/test_telemetry.py::Test_Defaults: missing_feature
  tests/parametric/test_telemetry.py::Test_Environment: missing_feature
  tests/parametric/test_telemetry.py::Test_Stable_Configuration_Origin: missing_feature
  tests/parametric/test_telemetry.py::Test_TelemetryInstallSignature: missing_feature
  tests/parametric/test_telemetry.py::Test_TelemetrySCAEnvVar: missing_feature
  tests/parametric/test_telemetry.py::Test_TelemetrySSIConfigs: missing_feature
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Basic: 0.0.1
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Globs: 0.0.1
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Globs_Feb2024_Revision: 0.0.1
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Resource: 0.0.1
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Tags: missing_feature
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_Tags_Feb2024_Revision: missing_feature
  tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_With_W3C: missing_feature
  tests/parametric/test_tracer.py: missing_feature
  tests/parametric/test_tracer_flare.py::TestTracerFlareV1: missing_feature
  tests/stats/test_stats.py: missing_feature
  tests/test_v1_payloads.py: missing_feature
