name: Push Feature Parity Metrics to datadog

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 23 * * *'

jobs:
  push_metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install requests datadog_api_client
      - name: Push metrics
        run: python utils/scripts/push-metrics.py
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
